// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE3QMsFUF2VYnLzfy24LCape793o8Aqmg',
    appId: '1:424737386450:web:50693470110466aff8620b',
    messagingSenderId: '424737386450',
    projectId: 'insta-clone-c2096',
    authDomain: 'insta-clone-c2096.firebaseapp.com',
    storageBucket: 'insta-clone-c2096.firebasestorage.app',
    measurementId: 'G-LEKB90DH3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOchllnCXn16Hi9w3LvGOuucj55YuA86Q',
    appId: '1:424737386450:android:bd9c2703f96d3961f8620b',
    messagingSenderId: '424737386450',
    projectId: 'insta-clone-c2096',
    storageBucket: 'insta-clone-c2096.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpIRVm_-d1xWgEjb7HiNNnm8QfcS6doFo',
    appId: '1:424737386450:ios:e4977d733319a60ff8620b',
    messagingSenderId: '424737386450',
    projectId: 'insta-clone-c2096',
    storageBucket: 'insta-clone-c2096.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpIRVm_-d1xWgEjb7HiNNnm8QfcS6doFo',
    appId: '1:424737386450:ios:e4977d733319a60ff8620b',
    messagingSenderId: '424737386450',
    projectId: 'insta-clone-c2096',
    storageBucket: 'insta-clone-c2096.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE3QMsFUF2VYnLzfy24LCape793o8Aqmg',
    appId: '1:424737386450:web:b7f834e69fe98846f8620b',
    messagingSenderId: '424737386450',
    projectId: 'insta-clone-c2096',
    authDomain: 'insta-clone-c2096.firebaseapp.com',
    storageBucket: 'insta-clone-c2096.firebasestorage.app',
    measurementId: 'G-FL2H9ZJL64',
  );
}
